
+ user with jwt token
+ product CRUD
+ rating, comment - review, 
+ swagger
+ permissions
+ media
+ favorits, dislike дз
+ pagination, filter, search дз
+ celery -> sudo apt install redis (добавить requirements.txt redis, celery)
+ карусель
+ cache
+ log
+ order
+ cors
+ admin

deploy
test
fake chat ?





